apiVersion: v1
kind: ConfigMap
metadata:
  name: bankfrontend002-conf
data:
  env: |
    NEXT_PUBLIC_NEST_API_URL=http://bankapi002-service:3000/api
    NEXT_PUBLIC_BANK_NAME=CTER
    NEXT_PUBLIC_BANK_CODE=002